import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Routes, Route, Navigate } from "react-router-dom";
// Halaman Penulis
import AuthorHome from "@/pages/dashboard/author/home/AuthorHome";
// Halaman Auth
import Login from "@/pages/dashboard/auth/Login";
// import Register from "@/pages/dashboard/auth/Register";
// Not Found
import NotFound from "@/pages/NotFound";
// Auth Route Guard
import RequireRoleRoute from "./RequireRoleRoute";
import AuthorLayout from "@/layout/AuthorLayout";
import TreasurerLayout from "@/layout/TreasurerLayout";
import AdminLayout from "@/layout/AdminLayout";
import TreasurerHome from "@/pages/dashboard/treasurer/home/TreasurerHome";
import AdminHome from "@/pages/dashboard/admin/home/AdminHome";
import MasjidLinkTree from "@/pages/linktree/MasjidLinkTreeHome";
import MasjidDonationMasjid from "@/pages/linktree/finansial/donation/MasjidDonation";
import MasjidLayout from "@/pages/linktree/MasjidLayout";
import MasjidDonationConfirmDonation from "@/pages/linktree/finansial/donation/MasjidDonationConfirmFinansial";
import MasjidProfile from "@/pages/linktree/profil/MasjidProfil";
import MasjidDKMPengajarProfil from "@/pages/linktree/profil/MasjidDKMPengajarProfil";
import MasjidDetailSpeech from "@/pages/linktree/profil/MasjidDetailSpeechProfil";
import MasjidProfileDetail from "@/pages/linktree/profil/MasjidDetailProfil";
import MasjidScheduleLecture from "@/pages/linktree/lecture/schedule/MasjidScheduleLectureSessions";
import MasjidDetailLecture from "@/pages/linktree/lecture/schedule/MasjidDetailScheduleLectureSessions";
import MasjidDonationMotivation from "@/pages/linktree/finansial/donation/MasjidDonationMotivation";
import MasjidLectureMaterial from "@/pages/linktree/lecture/material/lecture/main/MasjidLecture";
import MasjidInformationLectureSessions from "@/pages/linktree/lecture/material/lecture-sessions/main/MasjidInformationLectureSessions";
import MasjidQuizLectureSessions from "@/pages/linktree/lecture/material/lecture-sessions/quizzes/MasjidQuizLectureSessions";
import MasjidFullTranscriptLectureSessions from "@/pages/linktree/lecture/material/lecture-sessions/materials/MasjidFullTranscriptLectureSessions";
import MasjidSummaryLectureSessions from "@/pages/linktree/lecture/material/lecture-sessions/materials/MasjidSummaryLectureSessions";
import MasjidDocsLectureSessions from "@/pages/linktree/lecture/material/lecture-sessions/assets/MasjidDocsLectureSessions";
import MasjidResultQuizLectureSessions from "@/pages/linktree/lecture/material/lecture-sessions/quizzes/MasjidResultQuizLectureSessions";
import MasjidVideoAudioLectureSessions from "@/pages/linktree/lecture/material/lecture-sessions/assets/MasjidVideoAudioLectureSessions";
// import DKMAddEditSummaryLectureSessions from "@/pages/dashboard/dkm/lecture/lecture-sessions/materials/summary/DKMAddEditSummaryLectureSessions";
// import DKMProfilMasjidParent from "@/pages/dashboard/dkm/profile/DKMProfileParent";
import MasjidMaterial from "@/pages/linktree/lecture/material/MasjidMaterial";
import MasjidCertificateLecture from "@/pages/linktree/lecture/certificate/MasjidCertificate";
import MasjidDocsLecture from "@/pages/linktree/lecture/material/lecture/assets/MasjidDocsLecture";
import MasjidVideoAudioLecture from "@/pages/linktree/lecture/material/lecture/assets/MasjidVideoAudioLecture";
import MasjidQuizLecture from "@/pages/linktree/lecture/material/lecture/quizzes/MasjidQuizLecture";
import MasjidFullTransciptLecture from "@/pages/linktree/lecture/material/lecture/materials/MasjidFullTransciptLecture";
import MasjidSummaryLecture from "@/pages/linktree/lecture/material/lecture/materials/MasjidSummaryLecture";
import MasjidLectureSessions from "@/pages/linktree/lecture/material/lecture-sessions/main/MasjidLectureSessions";
import MasjidExamLecture from "@/pages/linktree/lecture/material/lecture/exams/MasjidExamLecture";
import MasjidResultExamLecture from "@/pages/linktree/lecture/material/lecture/exams/MasjidResultExamLecture";
import MasjidMyProfile from "@/pages/linktree/activity/setting/MasjidMyProfile";
import MasjidMyActivity from "@/pages/linktree/activity/my-activity/MasjidMyActivity";
import MasjidPost from "@/pages/linktree/post/main/MasjidPost";
// import MasjidDetailPost from "@/pages/linktree/post/main/MasjidDetailPost";
import MasjidDetailDonation from "@/pages/linktree/post/main/MasjidDetailMotivation";
import MasjidSettingLayout from "@/layout/masjid/MasjidSettingLayout";
import MasjidAppereance from "@/pages/linktree/activity/setting/MasjidAppereance";
import MasjidSupportUs from "@/pages/linktree/activity/setting/MasjidSupportUs";
import MasjidPartnership from "@/pages/linktree/activity/setting/MasjidPartnership";
import MasjidFaq from "@/pages/linktree/activity/setting/MasjidFaq";
import MasjidSettingMenu from "@/layout/masjid/MasjidSettingMenu";
import MasjidMyDonation from "@/pages/linktree/finansial/report/MasjidMyDonation";
import MasjidMyStats from "@/pages/linktree/activity/my-activity/MasjidMyStats";
import MasjidInformationLecture from "@/pages/linktree/lecture/material/lecture/main/MasjidInformationLecture";
import MasjidSholat from "@/pages/linktree/home/sholat/MasjidSholat";
import MasjidAllMyLecture from "@/pages/linktree/activity/my-activity/MasjidAllMyLecture";
import MasjidMyNotesLectureSessions from "@/pages/linktree/lecture/material/lecture-sessions/arsip/MasjidMyNotesLectureSessions";
import MasjidkuHome from "@/pages/masjidku/MasjidkuHome";
import MasjidMaterialByMonth from "@/pages/linktree/lecture/material/lecture-sessions-by-month/MasjidLectureSessionsByMonth";
import MasjidDetailSummaryLecture from "@/pages/linktree/lecture/material/lecture/materials/MasjidDetailSummaryLecture";
import MasjidDetailDKMPengajarMobile from "@/pages/linktree/profil/MasjidDetailDKMPengajarProfilMobile";
import MasjidkuLayout from "@/layout/MasjidkuLayout";
import MasjidkuFinancial from "@/pages/masjidku/financial/MasjidkuFinacial";
import MasjidkuListMasjid from "@/pages/masjidku/masjid/MasjidkuListMasjid";
import MasjidkuProfil from "@/pages/masjidku/profil/MasjidkuProfil";
import MasjidkuProgram from "@/pages/masjidku/program/MasjidkuProgram";
import StudentProgressDetail from "@/pages/sekolahislamku/dashboard-student/progress/StudentProgress";
import StudentDashboard from "@/pages/sekolahislamku/dashboard-student/StudentDashboard";
import StudentFInance from "@/pages/sekolahislamku/dashboard-student/finance/StudentFinance";
import StudentSchedule from "@/pages/sekolahislamku/dashboard-student/schedule/StudentSchedule";
import StudentAnnouncement from "@/pages/sekolahislamku/dashboard-student/announcement/StudentAnnouncement";
import StudentRaport from "@/pages/sekolahislamku/dashboard-student/progress/raport/StudentRaport";
import StudentNotesSummary from "@/pages/sekolahislamku/dashboard-student/progress/notes-summary/StudentNotesSummary";
import StudentAbsence from "@/pages/sekolahislamku/dashboard-student/progress/absence/StudentAbsence";
import StudentLayout from "@/layout/StudentLayout";
import TeacherDashboard from "@/pages/sekolahislamku/dashboard-teacher/TeacherDashboard";
import SchoolDashboard from "@/pages/sekolahislamku/dashboard-school/SchoolDashboard";
import TeacherClass from "@/pages/sekolahislamku/dashboard-teacher/class/TeacherClass";
import TeacherAttendance from "@/pages/sekolahislamku/dashboard-teacher/attendance/TeacherAttendance";
import TeacherGrading from "@/pages/sekolahislamku/dashboard-teacher/grade/TeacherGrade";
import TeacherAnnouncements from "@/pages/sekolahislamku/dashboard-teacher/announcement/TeacherAnnouncement";
import SchoolStudent from "@/pages/sekolahislamku/dashboard-school/student-(pending)/SchoolStudent";
import SchoolTeacher from "@/pages/sekolahislamku/dashboard-school/teacher/SchoolTeacher";
import SchoolClasses from "@/pages/sekolahislamku/dashboard-school/class/SchoolClass";
import SchoolAttendance from "@/pages/sekolahislamku/dashboard-school/attendance-(pending)/SchoolAttendance";
import SchoolFinance from "@/pages/sekolahislamku/dashboard-school/finance/SchoolFinance";
import SchoolAnnouncement from "@/pages/sekolahislamku/dashboard-school/announcement/SchoolAnnouncement";
import StudentDetailAnnouncement from "@/pages/sekolahislamku/dashboard-student/announcement/StudentDetailAnnouncement";
import TeacherSchedule from "@/pages/sekolahislamku/dashboard-teacher/schedule/TeacherSchedule";
import TeacherClassAttendance from "@/pages/sekolahislamku/dashboard-teacher/class/TeacherClassAttendance";
// School Routes
import AllSchedule from "@/pages/sekolahislamku/dashboard-school/dashboard/AllSchedule";
import AllAnnouncement from "@/pages/sekolahislamku/dashboard-school/dashboard/AllAnnouncement";
import AllInvoices from "@/pages/sekolahislamku/dashboard-school/dashboard/AllInvoices";
import TryoutTahfizhExam from "@/pages/sekolahislamku/dashboard-school/dashboard/TryoutTahfizhExam";
import { financeRoutes } from "@/pages/masjidku/financial/routes";
import SchoolManageClass from "@/pages/sekolahislamku/dashboard-school/class/detail/SchoolDetailClass";
import SchoolBooks from "@/pages/sekolahislamku/dashboard-school/books/SchoolBooks";
import SchoolDetailBook from "@/pages/sekolahislamku/dashboard-school/books/detail/SchoolDetailBook";
import AllAnnouncementTeacher from "@/pages/sekolahislamku/dashboard-teacher/dashboard/AllAnnouncementTeacher";
import ScheduleThreeDays from "@/pages/sekolahislamku/dashboard-teacher/class/components/ScheduleThreeDays";
import AllAssignment from "@/pages/sekolahislamku/dashboard-teacher/class/components/AllAssignment";
import DetailMateri from "@/pages/sekolahislamku/dashboard-teacher/class/components/DetailMateri";
import MasjidkuWebHome from "@/pages/masjidku/website/MasjidkuWebHome";
import RegisterAdminMasjid from "@/pages/dashboard/auth/register/RegisterAdminMasjid";
import RegisterUser from "@/pages/dashboard/auth/register/RegisterUser";
import RegisterDetailAdminMasjid from "@/pages/dashboard/auth/register/RegisterDetailAdminMasjid";
import DetailScheduleThreeDays from "@/pages/sekolahislamku/dashboard-teacher/class/components/DetailScheduleThreeDays";
import ScheduleSevenDays from "@/pages/sekolahislamku/dashboard-teacher/class/components/ScheduleSevenDays";
import DetailScheduleSevenDays from "@/pages/sekolahislamku/dashboard-teacher/class/components/DetailScheduleSevenDays";
import DetailSchedule from "@/pages/sekolahislamku/dashboard-school/dashboard/DetailSchedule";
import DetailAnnouncementTeacher from "@/pages/sekolahislamku/dashboard-teacher/dashboard/DetailAnnouncementTeacher";
import ManagementClass from "@/pages/sekolahislamku/dashboard-teacher/dashboard/ManagementClass";
import HomeroomTeacher from "@/pages/sekolahislamku/dashboard-teacher/class/components/HomeroomTeacher";
import TaskScore from "@/pages/sekolahislamku/dashboard-teacher/class/components/TaskScore";
import AttendanceManagement from "@/pages/sekolahislamku/dashboard-teacher/class/components/AttendanceManagement";
import DetailStudent from "@/pages/sekolahislamku/dashboard-teacher/class/components/DetailStudent";
import StudentScore from "@/pages/sekolahislamku/dashboard-teacher/class/components/StudentScore";
import AttendanceDetail from "@/pages/sekolahislamku/dashboard-teacher/attendance/components/AttendanceDetail";
import DetailGrading from "@/pages/sekolahislamku/dashboard-teacher/grade/components/DetailGrading";
import StudentDetail from "@/pages/sekolahislamku/dashboard-student/dashboard/StudentDetail";
import ListFinance from "@/pages/sekolahislamku/dashboard-student/dashboard/ListFinnance";
import InvoiceTagihan from "@/pages/sekolahislamku/dashboard-student/dashboard/InvoiceTagihan";
import AnnouncementsStudent from "@/pages/sekolahislamku/dashboard-student/dashboard/AnnouncementsStudent";
import AllScheduleStudent from "@/pages/sekolahislamku/dashboard-student/dashboard/AllScheduleStudent";
import DetailScheduleStudent from "@/pages/sekolahislamku/dashboard-student/dashboard/DetailScheduleStudent";
import DetailClass from "@/pages/sekolahislamku/dashboard-teacher/class/components/DetailClass";
import ClassAttandence from "@/pages/sekolahislamku/dashboard-teacher/class/components/ClassAttandence";
import ClassMateri from "@/pages/sekolahislamku/dashboard-teacher/class/components/ClassMateri";
import AssignmentClass from "@/pages/sekolahislamku/dashboard-teacher/class/components/AssignmentClass";
import DetailAssignmentClass from "@/pages/sekolahislamku/dashboard-teacher/class/components/DetailAssignmentClass";
import Bill from "@/pages/sekolahislamku/dashboard-school/finance/Bill";
import DetailAnnouncementStudent from "@/pages/sekolahislamku/dashboard-student/dashboard/DetailAnnouncementStudent";
import SchoolProfile from "@/pages/sekolahislamku/dashboard-school/profile/SchoolProfile";
import AcademicSchool from "@/pages/sekolahislamku/dashboard-school/academic/AcademicSchool";
import DetailAcademic from "@/pages/sekolahislamku/dashboard-school/academic/components/DetailAcademic";
import ManagementAcademic from "@/pages/sekolahislamku/dashboard-school/academic/components/ManagementAcademic";
import SchoolMenuGrids from "@/pages/sekolahislamku/dashboard-school/menu-utama/SchoolMenuGrids";
import TeacherMenuGrids from "@/pages/sekolahislamku/dashboard-teacher/menu-utama/TeacherMenuGrids";
import StudentMenuGrids from "@/pages/sekolahislamku/dashboard-student/menu-utama/StudentMenuGrids";
import RoomSchool from "@/pages/sekolahislamku/dashboard-school/menu-utama/components/RoomSchool";
import SchoolSpp from "@/pages/sekolahislamku/dashboard-school/spp/SchoolSpp";
import SchoolSubject from "@/pages/sekolahislamku/dashboard-school/subject/SchoolSubject";
import SchoolCertificate from "@/pages/sekolahislamku/dashboard-school/certificate/SchoolCertificate";
import DetailCertificate from "@/pages/sekolahislamku/dashboard-school/certificate/components/DetailCertificate";
import CalenderAcademic from "@/pages/sekolahislamku/dashboard-school/calender/CalenderAcademic";
import SchoolStatistik from "@/pages/sekolahislamku/dashboard-school/statistik/SchoolStatistik";
import SchoolSettings from "@/pages/sekolahislamku/dashboard-school/settings/SchoolSettings";
import SchoolActiveClass from "@/pages/sekolahislamku/dashboard-school/active-class/SchoolActiveClass";
import AllClasses from "@/pages/sekolahislamku/dashboard-teacher/menu-utama/AllClasses";
import ClassDetail from "@/pages/sekolahislamku/dashboard-teacher/menu-utama/DetailClasses";
import TeacherProfil from "@/pages/sekolahislamku/dashboard-teacher/profil/TeacherProfil";
import TeacherSettings from "@/pages/sekolahislamku/dashboard-teacher/menu-utama/settings/TeacherSettings";
import TeacherAssignment from "@/pages/sekolahislamku/dashboard-teacher/menu-utama/assignments/TeacherAssignment";
import TeacherCertificate from "@/pages/sekolahislamku/dashboard-teacher/menu-utama/certificate/Certificate";
import DetailTeacher from "@/pages/sekolahislamku/dashboard-school/teacher/components/DetailTeacher";
import StudentProfil from "@/pages/sekolahislamku/dashboard-student/profil/StudentProfil";
import StudentCertificate from "@/pages/sekolahislamku/dashboard-student/certificate/StudentCertificate";
import DetailBill from "@/pages/sekolahislamku/dashboard-school/finance/DetailBill";
import DetailRoomSchool from "@/pages/sekolahislamku/dashboard-school/menu-utama/components/DetailRoomSchool";
import SupportPage from "@/pages/masjidku/website/pages/navbar-page/support";
import Panduan from "@/pages/masjidku/website/pages/navbar-page/panduan";
import Fitur from "@/pages/masjidku/website/pages/navbar-page/fitur";
import About from "@/pages/masjidku/website/pages/navbar-page/about";
import Contact from "@/pages/masjidku/website/pages/navbar-page/contact";
import QuizPage from "@/pages/sekolahislamku/dashboard-school/class/components/QuizPage";
import QuizDetailPage from "@/pages/sekolahislamku/dashboard-school/class/components/QuizDetailPage";
import DetailClassQuiz from "@/pages/sekolahislamku/dashboard-teacher/class/components/DetailClassQuiz";
import MyClass from "@/pages/sekolahislamku/dashboard-student/class/MyClass";
import StudentMateri from "@/pages/sekolahislamku/dashboard-student/class/StudentMateri";
import StudentAssignment from "@/pages/sekolahislamku/dashboard-student/class/StudentAssignment";
import StudentQuizPage from "@/pages/sekolahislamku/dashboard-student/class/QuizPage";
import StudentExam from "@/pages/sekolahislamku/dashboard-student/class/StudentExam";
import StudentAssignmentClass from "@/pages/sekolahislamku/dashboard-student/assignment/StudentAssignmentClass";
import StudentAttandenceClass from "@/pages/sekolahislamku/dashboard-student/class/StudentAttandenceClass";
import Unauthorized from "./UnAuthorized";
// import { schoolRoutes } from "@/pages/sekolahislamku/dashboard-school/routes";
export default function AppRoutes() {
    return (_jsxs(Routes, { children: [_jsxs(Route, { element: _jsx(MasjidkuLayout, {}), children: [_jsx(Route, { index: true, element: _jsx(MasjidkuHome, {}) }), _jsx(Route, { path: "finansial", element: _jsx(MasjidkuFinancial, {}) }), _jsx(Route, { path: "masjid", element: _jsx(MasjidkuListMasjid, {}) }), _jsx(Route, { path: "profil", element: _jsx(MasjidkuProfil, {}) }), _jsx(Route, { path: "website", element: _jsx(MasjidkuWebHome, {}) }), _jsx(Route, { path: "website/dukungan", element: _jsx(SupportPage, {}) }), _jsx(Route, { path: "website/panduan", element: _jsx(Panduan, {}) }), _jsx(Route, { path: "website/fitur", element: _jsx(Fitur, {}) }), _jsx(Route, { path: "website/about", element: _jsx(About, {}) }), _jsx(Route, { path: "website/hubungi-kami", element: _jsx(Contact, {}) }), _jsx(Route, { path: "program", element: _jsx(MasjidkuProgram, {}) }), financeRoutes.map((route, index) => (_jsx(Route, { path: route.path.replace("/masjidku/", ""), element: route.element }, index)))] }), _jsx(Route, { path: "/login", element: _jsx(Login, {}) }), _jsx(Route, { path: "/website/daftar-sekarang", element: _jsx(RegisterAdminMasjid, {}) }), _jsx(Route, { path: "/register-detail-sekolah", element: _jsx(RegisterDetailAdminMasjid, {}) }), _jsx(Route, { path: "/register-user", element: _jsx(RegisterUser, {}) })
            // 1. Tanpa layout untuk LinkTree
            , "// 1. Tanpa layout untuk LinkTree", _jsx(Route, { path: "masjid/:slug", index: true, element: _jsx(MasjidLinkTree, {}) })
            // 2. Dengan layout untuk halaman lainnya
            , "// 2. Dengan layout untuk halaman lainnya", _jsx(Route, { path: "/", element: _jsx(MasjidLayout, {}), children: _jsxs(Route, { path: "masjid/:slug", children: [_jsx(Route, { path: "login", element: _jsx(Login, {}) }), _jsx(Route, { path: "register-masjid", element: _jsx(RegisterAdminMasjid, {}) }), _jsxs(Route, { path: "profil", children: [_jsx(Route, { index: true, element: _jsx(MasjidProfile, {}) }), _jsx(Route, { path: "dkm-pengajar", element: _jsx(MasjidDKMPengajarProfil, {}) }), _jsx(Route, { path: "sambutan", element: _jsx(MasjidDetailSpeech, {}) }), _jsxs(Route, { path: "dkm-pengajar", children: [_jsx(Route, { index: true, element: _jsx(MasjidDKMPengajarProfil, {}) }), _jsx(Route, { path: "detail/:id", element: _jsx(MasjidDetailDKMPengajarMobile, {}) })] }), _jsx(Route, { path: "detail", element: _jsx(MasjidProfileDetail, {}) })] }), _jsx(Route, { path: "sholat", element: _jsx(MasjidSholat, {}) }), _jsx(Route, { path: "donasi", element: _jsx(MasjidDonationMasjid, {}) }), _jsx(Route, { path: "donasi/konfirmasi", element: _jsx(MasjidDonationConfirmDonation, {}) }), _jsx(Route, { path: "donasi/pesan", element: _jsx(MasjidDonationMotivation, {}) }), _jsx(Route, { path: "jadwal-kajian", element: _jsx(MasjidScheduleLecture, {}) }), _jsx(Route, { path: "jadwal-kajian/:id", element: _jsx(MasjidDetailLecture, {}) }), _jsx(Route, { path: "soal-materi", element: _jsx(MasjidMaterial, {}) }), _jsx(Route, { path: "soal-materi/:lecture_session_slug", element: _jsx(MasjidLectureSessions, {}) }), _jsx(Route, { path: "soal-materi/:lecture_session_slug/informasi", element: _jsx(MasjidInformationLectureSessions, {}) }), _jsx(Route, { path: "soal-materi/:lecture_session_slug/latihan-soal", element: _jsx(MasjidQuizLectureSessions, {}) }), _jsx(Route, { path: "soal-materi/:lecture_session_slug/latihan-soal/hasil", element: _jsx(MasjidResultQuizLectureSessions, {}) }), _jsx(Route, { path: "soal-materi/:lecture_session_slug/video-audio", element: _jsx(MasjidVideoAudioLectureSessions, {}) }), _jsx(Route, { path: "soal-materi/:lecture_session_slug/materi-lengkap", element: _jsx(MasjidFullTranscriptLectureSessions, {}) }), _jsx(Route, { path: "soal-materi/:lecture_session_slug/ringkasan", element: _jsx(MasjidSummaryLectureSessions, {}) }), _jsx(Route, { path: "soal-materi/:lecture_session_slug/catatanku", element: _jsx(MasjidMyNotesLectureSessions, {}) }), _jsx(Route, { path: "soal-materi/:lecture_session_slug/dokumen", element: _jsx(MasjidDocsLectureSessions, {}) }), _jsx(Route, { path: "materi-bulan/:month", element: _jsx(MasjidMaterialByMonth, {}) }), _jsx(Route, { path: "tema/:lecture_slug", element: _jsx(MasjidLectureMaterial, {}) }), _jsx(Route, { path: "tema/:lecture_slug/informasi", element: _jsx(MasjidInformationLecture, {}) }), _jsx(Route, { path: "tema/:lecture_slug/certificate/:user_exam_id", element: _jsx(MasjidCertificateLecture, {}) }), _jsx(Route, { path: "tema/:lecture_slug/dokumen", element: _jsx(MasjidDocsLecture, {}) }), _jsx(Route, { path: "tema/:lecture_slug/video-audio", element: _jsx(MasjidVideoAudioLecture, {}) }), _jsx(Route, { path: "tema/:lecture_slug/ujian", element: _jsx(MasjidExamLecture, {}) }), _jsx(Route, { path: "tema/:lecture_slug/ujian/hasil", element: _jsx(MasjidResultExamLecture, {}) }), _jsx(Route, { path: "tema/:lecture_slug/latihan-soal", element: _jsx(MasjidQuizLecture, {}) }), _jsx(Route, { path: "tema/:lecture_slug/materi-lengkap", element: _jsx(MasjidFullTransciptLecture, {}) }), _jsx(Route, { path: "tema/:lecture_slug/ringkasan", element: _jsx(MasjidSummaryLecture, {}) }), _jsx(Route, { path: "tema/:lecture_slug/ringkasan/detail", element: _jsx(MasjidDetailSummaryLecture, {}) }), " ", _jsx(Route, { path: "post", element: _jsx(MasjidPost, {}) }), _jsx(Route, { path: "motivation/:id", element: _jsx(MasjidDetailDonation, {}) }), _jsx(Route, { path: "aktivitas", element: _jsx(MasjidMyActivity, {}) }), _jsx(Route, { path: "aktivitas/kajian-saya", element: _jsx(MasjidAllMyLecture, {}) }), _jsx(Route, { path: "aktivitas/donasi-saya", element: _jsx(MasjidMyDonation, {}) }), _jsx(Route, { path: "aktivitas/statistik-saya", element: _jsx(MasjidMyStats, {}) }), _jsxs(Route, { path: "aktivitas/pengaturan", element: _jsx(MasjidSettingLayout, {}), children: [_jsx(Route, { path: "menu", element: _jsx(MasjidSettingMenu, {}) }), _jsx(Route, { path: "profil-saya", element: _jsx(MasjidMyProfile, {}) }), _jsx(Route, { path: "tampilan", element: _jsx(MasjidAppereance, {}) }), _jsx(Route, { path: "dukung-kami", element: _jsx(MasjidSupportUs, {}) }), _jsx(Route, { path: "kerjasama", element: _jsx(MasjidPartnership, {}) }), _jsx(Route, { path: "tanya-jawab", element: _jsx(MasjidFaq, {}) })] })] }) }), _jsx(Route, { element: _jsx(RequireRoleRoute, { allowedRoles: ["author"] }), children: _jsx(Route, { path: "/author", element: _jsx(AuthorLayout, {}), children: _jsx(Route, { index: true, element: _jsx(AuthorHome, {}) }) }) }), _jsx(Route, { element: _jsx(RequireRoleRoute, { allowedRoles: ["treasurer"] }), children: _jsx(Route, { path: "/treasurer", element: _jsx(TreasurerLayout, {}), children: _jsx(Route, { index: true, element: _jsx(TreasurerHome, {}) }) }) }), _jsx(Route, { element: _jsx(RequireRoleRoute, { allowedRoles: ["admin"] }), children: _jsx(Route, { path: "/admin", element: _jsx(AdminLayout, {}), children: _jsx(Route, { index: true, element: _jsx(AdminHome, {}) }) }) }), _jsxs(Route, { path: ":slug/murid", element: _jsx(StudentLayout, {}), children: [_jsx(Route, { index: true, element: _jsx(StudentDashboard, {}) }), _jsx(Route, { path: "progress", element: _jsx(StudentProgressDetail, {}) }), _jsx(Route, { path: "all-schedule", element: _jsx(AllScheduleStudent, {}) }), _jsx(Route, { path: "profil-murid", element: _jsx(StudentProfil, {}) }), _jsx(Route, { path: "tugas", element: _jsx(StudentAssignmentClass, {}) }), _jsx(Route, { path: "all-schedule/detail/:scheduleId", element: _jsx(DetailScheduleStudent, {}) }), _jsx(Route, { path: "announcements", element: _jsx(AnnouncementsStudent, {}) }), _jsx(Route, { path: "announcements/:id", element: _jsx(DetailAnnouncementStudent, {}) }), _jsx(Route, { path: "tagihan/:id", element: _jsx(InvoiceTagihan, {}) }), _jsx(Route, { path: "progress/raport", element: _jsx(StudentRaport, {}) }), _jsx(Route, { path: "detail", element: _jsx(StudentDetail, {}) }), _jsx(Route, { path: "finance", element: _jsx(StudentFInance, {}) }), _jsx(Route, { path: "jadwal", element: _jsx(StudentSchedule, {}) }), _jsx(Route, { path: "finnance-list", element: _jsx(ListFinance, {}) }), _jsx(Route, { path: "finnance-list/:id", element: _jsx(InvoiceTagihan, {}) }), _jsxs(Route, { path: "pengumuman", children: [_jsx(Route, { index: true, element: _jsx(StudentAnnouncement, {}) }), _jsx(Route, { path: "detail/:id", element: _jsx(StudentDetailAnnouncement, {}) })] }), _jsx(Route, { path: "progress/absensi", element: _jsx(StudentAbsence, {}) }), _jsx(Route, { path: "progress/catatan-hasil", element: _jsx(StudentNotesSummary, {}) }), _jsxs(Route, { path: "menu-utama", children: [_jsx(Route, { index: true, element: _jsx(StudentMenuGrids, {}) }), _jsx(Route, { path: "menu-utama", element: _jsx(StudentMenuGrids, {}) }), _jsx(Route, { path: "announcements", element: _jsx(AnnouncementsStudent, {}) }), _jsx(Route, { path: "my-class", element: _jsx(MyClass, {}) }), _jsx(Route, { path: "my-class/:id/materi", element: _jsx(StudentMateri, {}) }), _jsx(Route, { path: "my-class/:id/tugas", element: _jsx(StudentAssignment, {}) }), _jsx(Route, { path: "my-class/:id/quiz", element: _jsx(StudentQuizPage, {}) }), _jsx(Route, { path: "my-class/:id/kehadiran", element: _jsx(StudentAttandenceClass, {}) }), _jsx(Route, { path: "my-class/:id/ujian", element: _jsx(StudentExam, {}) }), _jsx(Route, { path: "progress/raport", element: _jsx(StudentRaport, {}) }), _jsx(Route, { path: "progress/absensi", element: _jsx(StudentAbsence, {}) }), _jsx(Route, { path: "progress/catatan-hasil", element: _jsx(StudentNotesSummary, {}) }), _jsx(Route, { path: "jadwal", element: _jsx(StudentSchedule, {}) }), _jsx(Route, { path: "finance", element: _jsx(StudentFInance, {}) }), _jsx(Route, { path: "finnance-list", element: _jsx(ListFinance, {}) }), _jsx(Route, { path: "finnance-list/:id", element: _jsx(InvoiceTagihan, {}) }), _jsx(Route, { path: "profil-murid", element: _jsx(StudentProfil, {}) }), _jsx(Route, { path: "sertifikat-murid", element: _jsx(StudentCertificate, {}) })] })] }), _jsxs(Route, { path: ":slug/guru", element: _jsx(StudentLayout, {}), children: [_jsx(Route, { index: true, element: _jsx(TeacherDashboard, {}) }), _jsx(Route, { path: "kehadiran", element: _jsx(TeacherAttendance, {}) }), _jsx(Route, { path: "kehadiran/:id", element: _jsx(AttendanceDetail, {}) }), _jsx(Route, { path: "profil-guru", element: _jsx(TeacherProfil, {}) }), _jsx(Route, { path: "penilaian", element: _jsx(TeacherGrading, {}) }), _jsx(Route, { path: "penilaian/:id", element: _jsx(DetailGrading, {}) }), _jsx(Route, { path: "pengumuman", element: _jsx(TeacherAnnouncements, {}) }), _jsx(Route, { path: "quizClass/:id", element: _jsx(DetailClassQuiz, {}) }), _jsx(Route, { path: "jadwal", element: _jsx(TeacherSchedule, {}) }), _jsx(Route, { path: "assignments", element: _jsx(AllAssignment, {}) }), _jsx(Route, { path: "assignments/:id", element: _jsx(DetailStudent, {}) }), _jsx(Route, { path: "kelas/:id/score", element: _jsx(TaskScore, {}) }), _jsx(Route, { path: "attendance-management", element: _jsx(AttendanceManagement, {}) }), _jsx(Route, { path: "kelas/homeroom", element: _jsx(HomeroomTeacher, {}) }), _jsx(Route, { path: "all-announcement-teacher", element: _jsx(AllAnnouncementTeacher, {}) }), _jsx(Route, { path: "all-announcement-teacher/detail/:id", element: _jsx(DetailAnnouncementTeacher, {}) }), _jsx(Route, { path: "management-class/:name", element: _jsx(ManagementClass, {}) }), _jsxs(Route, { path: "schedule-3-hari", children: [_jsx(Route, { index: true, element: _jsx(ScheduleThreeDays, {}) }), _jsx(Route, { path: ":scheduleId", element: _jsx(DetailScheduleThreeDays, {}) })] }), _jsxs(Route, { path: "schedule-seven-days", children: [_jsx(Route, { index: true, element: _jsx(ScheduleSevenDays, {}) }), _jsx(Route, { path: ":scheduleId", element: _jsx(DetailScheduleSevenDays, {}) })] }), _jsx(Route, { path: "schedule-seven-days/*", element: _jsx(Navigate, { to: "../schedule-seven-days", replace: true }) }), _jsxs(Route, { path: "kelas", children: [_jsx(Route, { index: true, element: _jsx(TeacherClass, {}) }), _jsx(Route, { path: ":id", element: _jsx(DetailClass, {}) }), _jsx(Route, { path: ":id/absensi", element: _jsx(ClassAttandence, {}) }), _jsx(Route, { path: ":id/material/:materialId", element: _jsx(DetailMateri, {}) }), _jsx(Route, { path: ":id/materi", element: _jsx(ClassMateri, {}) }), _jsx(Route, { path: ":id/materi/quizClass/:quizId", element: _jsx(DetailClassQuiz, {}) }), _jsx(Route, { path: ":id/tugas", element: _jsx(AssignmentClass, {}) }), _jsx(Route, { path: ":id/assignment/:assignmentId", element: _jsx(DetailAssignmentClass, {}) }), _jsx(Route, { path: ":id/student/:studentId/score", element: _jsx(StudentScore, {}) }), _jsx(Route, { path: "jadwal", element: _jsx(TeacherSchedule, {}) }), _jsx(Route, { path: "kehadiran", element: _jsx(TeacherClassAttendance, {}) }), _jsxs(Route, { path: "schedule-seven-days", children: [_jsx(Route, { index: true, element: _jsx(ScheduleSevenDays, {}) }), _jsx(Route, { path: ":scheduleId", element: _jsx(DetailScheduleSevenDays, {}) })] }), _jsx(Route, { path: "schedule-7-hari/*", element: _jsx(Navigate, { to: "../schedule-seven-days", replace: true }) })] }), _jsxs(Route, { path: "menu-utama", children: [_jsx(Route, { index: true, element: _jsx(TeacherMenuGrids, {}) }), _jsxs(Route, { path: "all-classes", children: [_jsx(Route, { index: true, element: _jsx(AllClasses, {}) }), _jsx(Route, { path: ":id", element: _jsx(ClassDetail, {}) })] }), _jsx(Route, { path: "jadwal", element: _jsx(TeacherSchedule, { showBack: true }) }), _jsx(Route, { path: "profil-guru", element: _jsx(TeacherProfil, {}) }), _jsx(Route, { path: "pengaturan", element: _jsx(TeacherSettings, {}) }), _jsx(Route, { path: "tugas", element: _jsx(TeacherAssignment, {}) }), _jsx(Route, { path: "sertifikat", element: _jsx(TeacherCertificate, {}) }), _jsx(Route, { path: "all-announcement-teacher", element: _jsx(AllAnnouncementTeacher, {}) }), _jsxs(Route, { path: "kelas", children: [_jsx(Route, { index: true, element: _jsx(TeacherClass, { showBack: true }) }), _jsx(Route, { path: ":id", element: _jsx(DetailClass, {}) }), _jsx(Route, { path: ":id/absensi", element: _jsx(ClassAttandence, {}) }), _jsx(Route, { path: ":id/material/:materialId", element: _jsx(DetailMateri, {}) }), _jsx(Route, { path: ":id/materi", element: _jsx(ClassMateri, {}) }), _jsx(Route, { path: ":id/tugas", element: _jsx(AssignmentClass, {}) }), _jsx(Route, { path: ":id/assignment/:assignmentId", element: _jsx(DetailAssignmentClass, {}) }), _jsx(Route, { path: ":id/student/:studentId/score", element: _jsx(StudentScore, {}) }), _jsx(Route, { path: "jadwal", element: _jsx(TeacherSchedule, {}) }), _jsx(Route, { path: "kehadiran", element: _jsx(TeacherClassAttendance, {}) }), _jsxs(Route, { path: "schedule-seven-days", children: [_jsx(Route, { index: true, element: _jsx(ScheduleSevenDays, {}) }), _jsx(Route, { path: ":scheduleId", element: _jsx(DetailScheduleSevenDays, {}) })] }), _jsx(Route, { path: "schedule-7-hari/*", element: _jsx(Navigate, { to: "../schedule-seven-days", replace: true }) })] })] })] }), _jsxs(Route, { path: ":slug/sekolah", element: _jsx(StudentLayout, {}), children: [_jsx(Route, { index: true, element: _jsx(SchoolDashboard, {}) }), _jsx(Route, { path: "murid", element: _jsx(SchoolStudent, {}) }), _jsx(Route, { path: "all-schedule", element: _jsx(AllSchedule, {}) }), _jsx(Route, { path: "profil-sekolah", element: _jsx(SchoolProfile, {}) }), _jsx(Route, { path: "keuangan", element: _jsx(SchoolFinance, {}) }), _jsx(Route, { path: "keuangan/detail/:id", element: _jsx(DetailBill, {}) }), _jsxs(Route, { path: "guru", children: [_jsx(Route, { index: true, element: _jsx(SchoolTeacher, {}) }), _jsx(Route, { path: ":id", element: _jsx(DetailTeacher, {}) })] }), _jsxs(Route, { path: "academic", children: [_jsx(Route, { index: true, element: _jsx(AcademicSchool, {}) }), _jsx(Route, { path: "detail", element: _jsx(DetailAcademic, {}) }), _jsx(Route, { path: "manage", element: _jsx(ManagementAcademic, {}) })] }), _jsx(Route, { path: "all-schedule/detail/:scheduleId", element: _jsx(DetailSchedule, {}) }), _jsxs(Route, { path: "all-invoices", children: [_jsx(Route, { index: true, element: _jsx(AllInvoices, {}) }), _jsx(Route, { path: ":id", element: _jsx(Bill, {}) }), " "] }), _jsx(Route, { path: "tryout-tahfizh-exam", element: _jsx(TryoutTahfizhExam, {}) }), _jsx(Route, { path: "all-announcement", element: _jsx(AllAnnouncement, {}) }), _jsxs(Route, { path: "kelas", children: [_jsx(Route, { index: true, element: _jsx(SchoolClasses, {}) }), _jsx(Route, { path: "detail/:id", element: _jsx(SchoolManageClass, {}) }), _jsx(Route, { path: "quiz/:id", element: _jsx(QuizPage, {}) }), _jsx(Route, { path: "quiz/:id/do", element: _jsx(QuizDetailPage, {}) })] }), _jsx(Route, { path: "kehadiran", element: _jsx(SchoolAttendance, {}) }), _jsx(Route, { path: "pengumuman", element: _jsx(SchoolAnnouncement, {}) }), _jsxs(Route, { path: "buku", children: [_jsx(Route, { index: true, element: _jsx(SchoolBooks, {}) }), _jsx(Route, { path: "detail/:id", element: _jsx(SchoolDetailBook, {}) })] }), _jsxs(Route, { path: "menu-utama", children: [_jsx(Route, { index: true, element: _jsx(SchoolMenuGrids, {}) }), _jsx(Route, { path: "profil-sekolah", element: _jsx(SchoolProfile, { showBack: true }) }), _jsx(Route, { path: "keuangan", element: _jsx(SchoolFinance, { showBack: true }) }), _jsx(Route, { path: "keuangan/detail/:id", element: _jsx(DetailBill, {}) }), _jsx(Route, { path: "guru", element: _jsx(SchoolTeacher, { showBack: true }) }), _jsx(Route, { path: "all-announcement", element: _jsx(AllAnnouncement, {}) }), _jsx(Route, { path: "sekolah", element: _jsx(SchoolDashboard, { showBack: true }) }), _jsx(Route, { path: "room-school", element: _jsx(RoomSchool, {}) }), _jsx(Route, { path: "room-school/:id", element: _jsx(DetailRoomSchool, {}) }), _jsx(Route, { path: "spp", element: _jsx(SchoolSpp, {}) }), _jsx(Route, { path: "pelajaran", element: _jsx(SchoolSubject, {}) }), _jsx(Route, { path: "sertifikat", element: _jsx(SchoolCertificate, {}) }), _jsx(Route, { path: "kalender", element: _jsx(CalenderAcademic, {}) }), _jsx(Route, { path: "statistik", element: _jsx(SchoolStatistik, {}) }), _jsx(Route, { path: "pengaturan", element: _jsx(SchoolSettings, {}) }), _jsx(Route, { path: "kelas-aktif", element: _jsx(SchoolActiveClass, {}) }), _jsx(Route, { path: "sertifikat/detail/:classId/:studentId", element: _jsx(DetailCertificate, {}) }), _jsx(Route, { path: "murid", element: _jsx(SchoolStudent, { showBack: true }) }), _jsxs(Route, { path: "buku", children: [_jsx(Route, { index: true, element: _jsx(SchoolBooks, { showBack: true }) }), _jsx(Route, { path: "detail/:id", element: _jsx(SchoolDetailBook, {}) })] }), _jsxs(Route, { path: "kelas", children: [_jsx(Route, { index: true, element: _jsx(SchoolClasses, { showBack: true }) }), _jsx(Route, { path: "detail/:id", element: _jsx(SchoolManageClass, {}) })] }), _jsxs(Route, { path: "academic", children: [_jsx(Route, { index: true, element: _jsx(AcademicSchool, { showBack: true }) }), _jsx(Route, { path: "detail", element: _jsx(DetailAcademic, {}) }), _jsx(Route, { path: "manage", element: _jsx(ManagementAcademic, {}) })] })] })] }), _jsx(Route, { path: "*", element: _jsx(NotFound, {}) }), _jsx(Route, { path: "/unauthorized", element: _jsx(Unauthorized, {}) })] }));
}
