import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { pickTheme } from "@/constants/thema";
import useHtmlDarkMode from "@/hooks/useHTMLThema";
import ShimmerImage from "@/components/common/main/ShimmerImage";
export default function UserProfileCard({ name, role, signatureUrl, jabatan, bio, tambahan, socialMedias = [], onEdit, editText = "Edit Profil", }) {
    const { isDark, themeName } = useHtmlDarkMode();
    const theme = pickTheme(themeName, isDark);
    return (_jsxs("div", { className: "rounded-xl p-5 shadow-sm space-y-6", style: { backgroundColor: theme.white1, color: theme.black1 }, children: [_jsx("h1", { className: "text-2xl font-bold", children: "Profil Saya" }), _jsxs("div", { className: "space-y-1", children: [_jsx("h2", { className: "text-lg font-bold", children: name }), _jsx("p", { className: "text-sm", style: { color: theme.silver2 }, children: role }), signatureUrl && (_jsx(ShimmerImage, { src: signatureUrl, alt: "TTD", className: "w-20 mt-1 object-contain" }))] }), socialMedias.length > 0 && (_jsxs("div", { children: [_jsx("h3", { className: "text-sm font-semibold mb-1", children: "Sosial Media" }), _jsxs("div", { className: "flex items-center gap-2", children: [socialMedias.map((icon, idx) => (_jsx(ShimmerImage, { src: icon, alt: `icon-${idx}`, className: "w-5 h-5 object-contain" }, idx))), onEdit && (_jsx("button", { className: "ml-2 text-sm px-3 py-1 rounded font-medium transition", onClick: onEdit, style: {
                                    backgroundColor: theme.primary2,
                                    color: theme.primary,
                                }, children: "+ Edit" }))] })] })), jabatan && (_jsxs("div", { children: [_jsx("h3", { className: "text-sm font-semibold mb-1", children: "Jabatan" }), _jsx("p", { className: "text-sm", children: jabatan })] })), bio && (_jsxs("section", { children: [_jsx("h3", { className: "text-sm font-bold mb-1", children: "Profil Diri" }), _jsx("p", { className: "text-sm leading-relaxed", style: { color: theme.black2 }, children: bio })] })), tambahan && (_jsxs("section", { children: [_jsx("h3", { className: "text-sm font-bold mb-1", children: "Informasi Lainnya" }), tambahan.split("\n").map((line, idx) => (_jsx("p", { className: "text-sm leading-relaxed", style: { color: theme.black2 }, children: line }, idx)))] })), onEdit && (_jsx("div", { className: "pt-4", children: _jsx("button", { className: "px-4 py-2 rounded-lg text-sm font-medium transition", style: { backgroundColor: theme.primary, color: theme.white1 }, onClick: onEdit, children: editText }) }))] }));
}
