import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import PageHeaderUser from "@/components/common/home/PageHeaderUser";
import { useNavigate } from "react-router-dom";
import { pickTheme } from "@/constants/thema";
import useHtmlDarkMode from "@/hooks/useHTMLThema";
export default function MasjidkuProfil() {
    const navigate = useNavigate();
    const { isDark, themeName } = useHtmlDarkMode();
    const theme = pickTheme(themeName, isDark);
    return (_jsxs(_Fragment, { children: [_jsx(PageHeaderUser, { title: "Profil MasjidKu", onBackClick: () => navigate(`/`), withPaddingTop // aktifin padding top
                : true }), _jsxs("div", { className: "max-w-3xl mx-auto space-y-6 rounded-xl ", style: {
                    backgroundColor: theme.white1, // kartu latar mengikuti tema
                    borderColor: theme.white3, // garis halus
                }, children: [_jsxs("section", { children: [_jsx("h2", { className: "text-lg font-semibold mb-2", style: { color: theme.quaternary }, children: "Latar Belakang" }), _jsx("p", { className: "text-justify leading-relaxed", style: { color: theme.black1 }, children: "MasjidKu lahir dari kebutuhan untuk menghadirkan solusi digital yang memudahkan pengelolaan masjid di seluruh Indonesia. Di era modern, peran masjid tidak hanya sebatas tempat ibadah, tetapi juga sebagai pusat edukasi, sosial, dan pemberdayaan umat. Namun, banyak masjid yang masih mengandalkan sistem manual dalam pencatatan keuangan, pengelolaan jadwal kegiatan, dan komunikasi dengan jamaah." }), _jsx("p", { className: "text-justify leading-relaxed mt-3", style: { color: theme.black1 }, children: "Melihat tantangan tersebut, MasjidKu hadir sebagai platform digital yang memadukan kemudahan teknologi dengan nilai-nilai islami. Melalui aplikasi dan website, kami membantu masjid untuk menyampaikan informasi secara cepat, transparan, dan mudah diakses, sehingga jamaah dapat terhubung lebih erat dengan kegiatan masjidnya." })] }), _jsxs("section", { children: [_jsx("h2", { className: "text-lg font-semibold mb-2", style: { color: theme.quaternary }, children: "Tujuan" }), _jsxs("ul", { className: "list-disc pl-5 space-y-2 leading-relaxed mb-10", style: { color: theme.black1 }, children: [_jsx("li", { children: "Mempermudah pengurus masjid dalam mengelola kegiatan, jadwal sholat, kajian, dan acara lainnya secara digital." }), _jsx("li", { children: "Menyediakan sistem pencatatan dan pelaporan keuangan masjid yang transparan dan akuntabel, sehingga meningkatkan kepercayaan jamaah." }), _jsx("li", { children: "Memperkuat hubungan antara masjid dan jamaah melalui penyampaian informasi yang cepat, tepat, dan interaktif." }), _jsx("li", { children: "Mendukung program dakwah dan edukasi dengan memanfaatkan media digital yang mudah diakses oleh berbagai kalangan." }), _jsx("li", { children: "Menjadi wadah kolaborasi antar masjid untuk saling berbagi pengalaman, sumber daya, dan inspirasi dalam memajukan pelayanan kepada umat." })] })] })] })] }));
}
