import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Badge, Btn, } from "@/pages/sekolahislamku/components/ui/Primitives";
import MiniBar from "@/pages/sekolahislamku/components/ui/MiniBar";
const STATUS_BADGE = {
    hadir: "success",
    online: "info",
    sakit: "warning",
    alpa: "destructive",
    izin: "secondary",
};
export default function StudentsTable({ palette, rows, emptyText = "Tidak ada data siswa.", onDetail, onGrade, showIqra = true, showJuz = true, showLastScore = true, }) {
    return (_jsx("div", { className: "mt-4 overflow-x-auto", children: _jsxs("table", { className: "w-full text-sm", children: [_jsx("thead", { children: _jsxs("tr", { style: { color: palette.silver2 }, children: [_jsx("th", { className: "text-left py-2 pr-3 font-medium", children: "Nama" }), _jsx("th", { className: "text-left py-2 px-3 font-medium", children: "Status" }), showIqra && (_jsx("th", { className: "text-left py-2 px-3 font-medium", children: "Iqra" })), showJuz && (_jsx("th", { className: "text-left py-2 px-3 font-medium", children: "Juz" })), showLastScore && (_jsx("th", { className: "text-left py-2 px-3 font-medium", children: "Nilai Terakhir" })), _jsx("th", { className: "text-right py-2 pl-3 font-medium", children: "Aksi" })] }) }), _jsxs("tbody", { children: [rows.map((s) => (_jsxs("tr", { className: "border-t", style: { borderColor: palette.silver1 }, children: [_jsxs("td", { className: "py-3 pr-3", children: [_jsx("div", { className: "font-medium", children: s.name }), s.time && (_jsxs("div", { className: "text-xs", style: { color: palette.silver2 }, children: [s.mode === "online" ? "Online" : "Onsite", " \u2022 ", s.time] }))] }), _jsx("td", { className: "py-3 px-3", children: _jsx(Badge, { palette: palette, variant: s.statusToday ? STATUS_BADGE[s.statusToday] : "secondary", children: (s.statusToday ?? "-").toString().toUpperCase() }) }), showIqra && _jsx("td", { className: "py-3 px-3", children: s.iqraLevel ?? "-" }), showJuz && (_jsx("td", { className: "py-3 px-3", children: _jsxs("div", { className: "w-40", children: [_jsx(MiniBar, { palette: palette, label: undefined, value: s.juzProgress ?? 0, total: 30, showPercent: false, height: 6 }), _jsxs("div", { className: "text-xs", style: { color: palette.silver2 }, children: [(s.juzProgress ?? 0).toFixed(1), " / 30"] })] }) })), showLastScore && (_jsx("td", { className: "py-3 px-3", children: typeof s.lastScore === "number" ? s.lastScore : "-" })), _jsx("td", { className: "py-3 pl-3 text-right", children: _jsxs("div", { className: "inline-flex gap-2", children: [_jsx(Btn, { palette: palette, size: "sm", variant: "outline", onClick: () => onDetail?.(s.id), children: "Detail" }), _jsx(Btn, { palette: palette, size: "sm", variant: "quaternary", onClick: () => onGrade?.(s.id), children: "Nilai" })] }) })] }, s.id))), rows.length === 0 && (_jsx("tr", { children: _jsx("td", { colSpan: 5 + Number(showIqra) + Number(showJuz) + Number(showLastScore), className: "py-6 text-center", style: { color: palette.silver2 }, children: emptyText }) }))] })] }) }));
}
